### ISSUE TITLE
Crear repository y service Testimonio

### ISSUE THREAD

**Issue by DarioRv** [21Enzo17/TF-PV#11]
# Crear repository y service Testimonio
Se solicita crear un archivo repository y service que contengan funciones para la persistencia de datos.

## Funciones que se solicitan
1. Guardar un testimonio.
2. Editar un testimonio.
3. Eliminar un testimonio (colocando su propiedad `estado` en 0).
4. Listar los testimonios guardados en base de datos.

## Otros aspectos
* Considere usar query personalizadas en caso de que sean necesario
* Modifique el controller añadiendo peticiones get y post.
* Cree las páginas necesarias (por ejemplo: formularios, vistas, etc).
* Cree la documentación de las funciones a crear.

**Comment by NahuelCabral** [comment]
Se ha creado la capa repository y service de la pagina Testimonio
