### ISSUE TITLE
Crear controller y entidad/clase Testimonio

### ISSUE THREAD

**Issue by DarioRv** [21Enzo17/TF-PV#6]
# Crear controller y entidad/clase Testimonio
Se solicita la creación de un controller y entidad/clase para representar los testimonios.

## Características de la entidad/clase
Clase Testimonio, debe contar con los siguientes datos:
- Id
- Fecha
- Usuario (objeto de la clase usuario)
- Comentario

**Comment by NahuelCabral** [comment]
Se ha realizado controller y entity para la pagina Testimonio
